artifacts_root: gs://sma-proj-bucket/pipeline_root/artifacts/


data_ingestion:
  root_dir: gs://sma-proj-bucket/pipeline_root/artifacts/data_ingestion
  source_dir: gs://sma-proj-bucket/pipeline_root/data_artifacts
  calcTickers: True
  FETCH_REPO: True