artifacts_root: gs://<bucket-name>/pipeline_root/artifacts/


data_ingestion:
  root_dir: gs://<bucket-name>/pipeline_root/artifacts/data_ingestion
  source_dir: gs://<bucket-name>/pipeline_root/data_artifacts
  calcTickers: False  ## if true calulate list of NSE stocks based on company financials filters
  FETCH_REPO: True  ## if false fetch data from data_ingestion folder


data_transformation:
  root_dir: gs://<bucket-name>/pipeline_root/artifacts/data_transformation
  data_path: gs://<bucket-name>/pipeline_root/artifacts/data_ingestion
  TRANSFORM_DATA: True ## if false fetch data from data_transormation folder


model_trainer:
  root_dir: gs://<bucket-name>/pipeline_root/artifacts/model_trainer
  num_trials: 5  ## number of trials for hyperopt
  cv: 2   ## cv count
  data_path: gs://<bucket-name>/pipeline_root/artifacts/data_transformation
  mlflow_uri: "http://<external ip address VM>:5000"   #"http://127.0.0.1:5000"    ## external ip address of the VM
  hpo_exp_rf: "random-forest-hyperParamTune v2"
  hpo_exp_xgb: "xgBoost-hyperParamTune v2"
  trainModel: True  ## if false dont train, use previously trained models from mlflow


model_evaluation:
  root_dir: gs://<bucket-name>/pipeline_root/artifacts/model_evaluation
  data_path: gs://<bucket-name>/pipeline_root/artifacts/data_transformation
  top_n: 3        ## top n models based on train score which are further evaluated based on test and val scores
  ml_uri: "http://<external ip address VM>:5000"   #"http://127.0.0.1:5000"     ## external ip address of the VM
  hpo_exp_rf: "random-forest-hyperParamTune v2"
  hpo_exp_xgb: "xgBoost-hyperParamTune v2"
  exp_name: "best-models v2"
  trainModel: True   ## if false dont train, use previously trained models from mlflow


model_prediction:
  root_dir: gs://<bucket-name>/pipeline_root/artifacts/model_preds
  data_path: gs://<bucket-name>/pipeline_root/artifacts/data_transformation
  ml_uri: "http://<external ip address VM>:5000"   #"http://127.0.0.1:5000"   ## external ip address of the VM
  hpo_exp_rf: "random-forest-hyperParamTune v2"
  hpo_exp_xgb: "xgBoost-hyperParamTune v2"
  exp_name: "best-models v2"
  model_name_xgb: "best-model-xgb"
  model_name_rf: "best-model-rf"
  prediction_name: "pred_xgp_rf_best"


model_monitoring:
  root_dir: gs://<bucket-name>/pipeline_root/artifacts/model_monitor
  data_path: gs://<bucket-name>/pipeline_root/artifacts/data_transformation
  ml_uri: "http://<external ip address VM>:5000"   #"http://127.0.0.1:5000"   #  ## external ip address of the VM
  exp_name: "best-models v2"
  model_name_xgb: "best-model-xgb"
  model_name_rf: "best-model-rf"
  prediction_name: "pred_xgp_rf_best"
  INSTANCE_CONNECTION_NAME: "<project-id>:<region-name>:<db name>"
  DB_USER: "DB_USER"
  DB_PASS: "DB_PASS"
  DB_NAME: "DB_NAME"
  TABLE_NAME: "TABLE_NAME"


simulate_strategy:
  root_dir: gs://<bucket-name>/pipeline_root/artifacts/simulate_strategy
  data_path: gs://<bucket-name>/pipeline_root/artifacts/model_preds
  rsi: 60
  prob_thres: 0.52
  LE1: 0.1
  LE2: 0.005
  SL: 0.001
  PP: 0.025
  window: 5
  starting_corpus: 1000000