channels:
- conda-forge
dependencies:
- python=3.10.8
- pip<=24.1.2
- pip:
  - mlflow==2.9.2
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==23.2
  - pyyaml==6.0.1
  - scikit-learn==1.4.2
  - scipy==1.13.1
name: mlflow-env
