name: Model prediction
description: Model prediction.
inputs:
  - name: config_path
    type: String
    description: The path to the configuration YAML file.
  - name: bucket_name
    type: String
    description: GCS bucket name.
implementation:
  container:
    image: <region-project-artifact>/mlops-model-pred-gcp:v1
    command: [
      "python", "predict.py",
      "--config", {inputValue: config_path},
      "--bucket", {inputValue: bucket_name}
    ]