name: ModelMonitoringComponent
description: A component to monitor data and model drift using Evidently AI and write metrics to PostgreSQL.
inputs:
  - name: config_path
    type: String
    description: The path to the configuration YAML file.
  - name: bucket_name
    type: String
    description: GCS bucket name.
implementation:
  container:
    image: <region-project-artifact>/mlops-model-monitor-gcp:v2
    command: [
      "python", "monitor.py",
      "--config", {inputValue: config_path},
      "--bucket", {inputValue: bucket_name}
    ]