artifacts_root: gs://sma-proj-bucket/pipeline_root/artifacts/


data_ingestion:
  root_dir: gs://sma-proj-bucket/pipeline_root/artifacts/data_ingestion
  source_dir: gs://sma-proj-bucket/pipeline_root/data_artifacts
  calcTickers: False
  FETCH_REPO: False



data_transformation:
  root_dir: gs://sma-proj-bucket/pipeline_root/artifacts/data_transformation
  data_path: gs://sma-proj-bucket/pipeline_root/artifacts/data_ingestion
  TRANSFORM_DATA: True