channels:
- conda-forge
dependencies:
- python=3.10.8
- pip<=24.1.2
- pip:
  - mlflow==2.9.2
  - numpy==1.26.4
  - pandas==2.0.3
  - scikit-learn==1.4.2
  - scipy==1.13.1
  - xgboost==2.0.3
name: mlflow-env
